### ISSUE TITLE
Configuration files are the same yet sync status reports "warn: passive node needs update"

### ISSUE THREAD

**Issue by Phoenixoboros** [opensvc/opensvc#178]
Hello,

Active node:

```
[phoenixoboros@fdja1p2 ~]# sudo rsync -avcn /etc/opensvc/ fdja2p2.lan.local:/etc/opensvc/
sending incremental file list

sent 473 bytes  received 20 bytes  986.00 bytes/sec
total size is 35,986  speedup is 72.99 (DRY RUN)
[phoenixoboros@fdja1p2 ~]#
```
```
[phoenixoboros@fdja1p2 ~]# sudo om CFJL print status --refresh
CFJL                                up         warn
`- instances
   |- fdja2p2.lan.local             stdby up   warn, idle
   `- fdja1p2.lan.local             up         warn, idle, started
      |- ip#0              .M.....3 up         172.16.7.210/255.255.255.0 bond0
      |- ip#1              .M.....3 up         172.16.6.220/255.255.255.0 bond1
      |- disk#0            ...../S. stdby up   drbd add-cfjl
      |                                        info: Primary
      |- disk#1            ...../S. stdby up   drbd pgsql-cfjl
      |                                        info: Primary
      |- disk#2            ...../S. stdby up   drbd amq-cfjl
      |                                        info: Primary
      |- disk#3            ...../S. stdby up   drbd journal-cfjl
      |                                        info: Primary
      |- fs#0              .M.....3 up         ext4 /dev/drbd0@/add
      |- fs#1              .M.....3 up         ext4 /dev/drbd1@/var/lib/pgsql
      |- fs#2              .M.....3 up         ext4 /dev/drbd2@/var/cfjl/amq
      |- fs#3              .M.....3 up         ext4 /dev/drbd3@/var/cfjl/journal
      |- app#0             .M.../.3 up         forking: postgresql-11
      |- app#1             .M.../.3 up         forking: JournalServer
      |- app#2             .M.../.3 up         forking: tomcat9
      |- app#3             .M.../.3 up         forking: cfjl_brokers_webapps
      |- app#4             .M.../.3 up         forking: cfjl
      |- app#5             .M.../.3 up         forking: httpd
      `- sync#i0           ...O./.. down       rsync svc config to nodes
                                               warn: fdja2p2.lan.local need update

[phoenixoboros@fdja1p2 ~]#
```

Passive node:

```
[phoenixoboros@fdja2p2 ~]# sudo om CFJL print status --refresh
CFJL                                up         warn
`- instances
   |- fdja1p2.lan.local             up         warn, idle, started
   `- fdja2p2.lan.local             stdby up   warn, idle
      |- ip#0              .M.....3 down       172.16.7.210/255.255.255.0 bond0
      |- ip#1              .M.....3 down       172.16.6.220/255.255.255.0 bond1
      |- disk#0            ...../S. stdby up   drbd add-cfjl
      |                                        info: Secondary
      |- disk#1            ...../S. stdby up   drbd pgsql-cfjl
      |                                        info: Secondary
      |- disk#2            ...../S. stdby up   drbd amq-cfjl
      |                                        info: Secondary
      |- disk#3            ...../S. stdby up   drbd journal-cfjl
      |                                        info: Secondary
      |- fs#0              .M.....3 down       ext4 /dev/drbd0@/add
      |- fs#1              .M.....3 down       ext4 /dev/drbd1@/var/lib/pgsql
      |- fs#2              .M.....3 down       ext4 /dev/drbd2@/var/cfjl/amq
      |- fs#3              .M.....3 down       ext4 /dev/drbd3@/var/cfjl/journal
      |- app#0             .M.../.3 n/a        forking: postgresql-11
      |                                        info: not evaluated (instance not up)
      |- app#1             .M.../.3 n/a        forking: JournalServer
      |                                        info: not evaluated (instance not up)
      |- app#2             .M.../.3 n/a        forking: tomcat9
      |                                        info: not evaluated (instance not up)
      |- app#3             .M.../.3 n/a        forking: cfjl_brokers_webapps
      |                                        info: not evaluated (instance not up)
      |- app#4             .M.../.3 n/a        forking: cfjl
      |                                        info: not evaluated (instance not up)
      |- app#5             .M.../.3 n/a        forking: httpd
      |                                        info: not evaluated (instance not up)
      `- sync#i0           ...O./.. warn       rsync svc config to nodes
                                               warn: passive node needs update

[phoenixoboros@fdja2p2 ~]#
```

**Comment by cvaroqui** [comment]
Hi,

sync#i0 does not only synchronize the service configuration file in /etc/opensvc/ but also service-private driver-specific information in /var/opensvc/.

It is not good practice to circumvent the sync driver anyway, as you may
1/ copy more files that the sync driver would have copied
2/ do not run postsync action

The correct way to fix the warning is "om CFJL sync nodes --rid sync#i0".

This command is normally scheduled (by default once per hour), so the warning should disappear automatically.

**Comment by Phoenixoboros** [comment]
Hi,

I had tried with sync nodes command, I got this:

```
om myapp sync nodes --rid sync#i0 --debug
@ n:servera1p2.lan.local
D raise nofile resource from 1024 limit to 4096
D session uuid: eea054a9-d4c8-47c5-bebe-bad752558d27
@ n:servera1p2.lan.local o:myapp r:ip#0 sc:n
D resolving 172.16.7.210
@ n:servera1p2.lan.local o:myapp r:ip#1 sc:n
D resolving 172.16.6.220
@ n:servera1p2.lan.local o:myapp sc:n
D resources initialized
D rids added from --rid sync#i0: sync#i0
D rids retained after expansions intersection: sync#i0
D purge all resource status file caches before action sync_nodes
D acquire service lock (timeout 60, delay 1, action sync_nodes, lockfile /var/lib/opensvc/svc/myapp/lock.generic.sync)
D resource sync#i0 can sync: True
D set_action: action=presync rset=ip
@ n:servera1p2.lan.local o:myapp rs:ip sc:n
D resources after tags[] filter: ip#0,ip#1
D resources after 'disable' filter: ip#0,ip#1
@ n:servera1p2.lan.local o:myapp r:ip#1 sc:n
D action: presync
D do action presync
@ n:servera1p2.lan.local o:myapp r:ip#0 sc:n
D action: presync
D do action presync
@ n:servera1p2.lan.local o:myapp sc:n
D set_action: action=presync rset=app
@ n:servera1p2.lan.local o:myapp rs:app sc:n
D resources after tags[] filter: app#5,app#4,app#1,app#0,app#3,app#2
D resources after 'disable' filter: app#5,app#4,app#1,app#0,app#3,app#2
@ n:servera1p2.lan.local o:myapp r:app#5 sc:n
D action: presync
D do action presync
@ n:servera1p2.lan.local o:myapp r:app#4 sc:n
D action: presync
D do action presync
@ n:servera1p2.lan.local o:myapp r:app#3 sc:n
D action: presync
D do action presync
@ n:servera1p2.lan.local o:myapp r:app#1 sc:n
D action: presync
D do action presync
@ n:servera1p2.lan.local o:myapp r:app#2 sc:n
D action: presync
D do action presync
@ n:servera1p2.lan.local o:myapp r:app#0 sc:n
D action: presync
D do action presync
@ n:servera1p2.lan.local o:myapp sc:n
D set_action: action=presync rset=disk
@ n:servera1p2.lan.local o:myapp rs:disk sc:n
D resources after tags[] filter: disk#0,disk#1,disk#2,disk#3
D resources after 'disable' filter: disk#0,disk#1,disk#2,disk#3
@ n:servera1p2.lan.local o:myapp r:disk#3 sc:n
D action: presync
D do action presync
@ n:servera1p2.lan.local o:myapp r:disk#2 sc:n
D action: presync
D do action presync
@ n:servera1p2.lan.local o:myapp r:disk#1 sc:n
D action: presync
D do action presync
@ n:servera1p2.lan.local o:myapp r:disk#0 sc:n
D action: presync
D do action presync
@ n:servera1p2.lan.local o:myapp sc:n
D set_action: action=presync rset=sync
@ n:servera1p2.lan.local o:myapp rs:sync sc:n
D resources after tags[] filter: sync#i0
D resources after 'disable' filter: sync#i0
@ n:servera1p2.lan.local o:myapp r:sync#i0 sc:n
D action: presync
D do action presync
D cache MISS: /var/lib/opensvc/cache/eea054a9-d4c8-47c5-bebe-bad752558d27/rsync.version
D cache PUT: /var/lib/opensvc/cache/eea054a9-d4c8-47c5-bebe-bad752558d27/rsync.version
@ n:servera1p2.lan.local o:myapp r:fs#0 sc:n
D cache MISS: /var/lib/opensvc/cache/eea054a9-d4c8-47c5-bebe-bad752558d27/dmsetup.ls.multipath
D cache PUT: /var/lib/opensvc/cache/eea054a9-d4c8-47c5-bebe-bad752558d27/dmsetup.ls.multipath
D refresh status: undef => up
@ n:servera1p2.lan.local o:myapp r:fs#1 sc:n
D cache GET: /var/lib/opensvc/cache/eea054a9-d4c8-47c5-bebe-bad752558d27/dmsetup.ls.multipath
D refresh status: undef => up
@ n:servera1p2.lan.local o:myapp r:fs#2 sc:n
D cache GET: /var/lib/opensvc/cache/eea054a9-d4c8-47c5-bebe-bad752558d27/dmsetup.ls.multipath
D refresh status: undef => up
@ n:servera1p2.lan.local o:myapp r:fs#3 sc:n
D cache GET: /var/lib/opensvc/cache/eea054a9-d4c8-47c5-bebe-bad752558d27/dmsetup.ls.multipath
D refresh status: undef => up
@ n:servera1p2.lan.local o:myapp r:ip#0 sc:n
D refresh status: undef => up
@ n:servera1p2.lan.local o:myapp r:ip#1 sc:n
D refresh status: undef => up
@ n:servera1p2.lan.local o:myapp r:disk#0 sc:n
D drbdadm dstate add-myapp
D output:
D | UpToDate/UpToDate
D refresh status: undef => stdby up
@ n:servera1p2.lan.local o:myapp r:disk#1 sc:n
D drbdadm dstate pgsql-myapp
D output:
D | UpToDate/UpToDate
D refresh status: undef => stdby up
@ n:servera1p2.lan.local o:myapp r:disk#2 sc:n
D drbdadm dstate amq-myapp
D output:
D | UpToDate/UpToDate
D refresh status: undef => stdby up
@ n:servera1p2.lan.local o:myapp r:disk#3 sc:n
D drbdadm dstate journal-myapp
D output:
D | UpToDate/UpToDate
D refresh status: undef => stdby up
@ n:servera1p2.lan.local o:myapp r:sync#i0 sc:n
D refresh status: undef => down
@ n:servera1p2.lan.local o:myapp sc:n
D set_action: action=presync rset=fs
@ n:servera1p2.lan.local o:myapp rs:fs sc:n
D resources after tags[] filter: fs#0,fs#1,fs#2,fs#3
D resources after 'disable' filter: fs#0,fs#1,fs#2,fs#3
@ n:servera1p2.lan.local o:myapp r:fs#1 sc:n
D action: presync
D do action presync
@ n:servera1p2.lan.local o:myapp r:fs#3 sc:n
D action: presync
D do action presync
@ n:servera1p2.lan.local o:myapp r:fs#2 sc:n
D action: presync
D do action presync
@ n:servera1p2.lan.local o:myapp r:fs#0 sc:n
D action: presync
D do action presync
@ n:servera1p2.lan.local o:myapp rs:sync sc:n
D start sync pre_action
D resources after tags[] filter: sync#i0
D resources after 'disable' filter: sync#i0
D snap not needed
@ n:servera1p2.lan.local o:myapp sc:n
D set_action: action=sync_nodes rset=sync
@ n:servera1p2.lan.local o:myapp rs:sync sc:n
D resources after tags[] filter: sync#i0
D resources after 'disable' filter: sync#i0
@ n:servera1p2.lan.local o:myapp r:sync#i0 sc:n
D action: sync_nodes
D do action sync_nodes
@ n:servera1p2.lan.local o:myapp r:disk#0 sc:n
E /etc/drbd.d/add-myapp.res does not exist
@ n:servera1p2.lan.local o:myapp r:disk#1 sc:n
E /etc/drbd.d/pgsql-myapp.res does not exist
@ n:servera1p2.lan.local o:myapp r:disk#2 sc:n
E /etc/drbd.d/amq-myapp.res does not exist
@ n:servera1p2.lan.local o:myapp r:disk#3 sc:n
E /etc/drbd.d/journal-myapp.res does not exist
@ n:servera1p2.lan.local o:myapp r:sync#i0 sc:n
D rsync -HAXpogDtrlvx --stats --delete --force -R --exclude=*.core --timeout=3600 -e /usr/bin/ssh -q -o StrictHostKeyChecking=no -o ForwardX11=no -o BatchMode=yes -o ConnectTimeout=10 /etc/opensvc/myapp.conf /etc/opensvc/myapp.d phoenixoboros@servera2p2.lan.local:/
E | rsync: rsync_xal_set: lremovexattr(""/etc/opensvc/myapp.conf"","security.selinux") failed: Permission denied (13)
E | rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1179) [sender=3.1.2]
D output:
D | sending incremental file list
D |
D | Number of files: 11 (reg: 8, dir: 3)
D | Number of created files: 0
D | Number of deleted files: 0
D | Number of regular files transferred: 0
D | Total file size: 35,710 bytes
D | Total transferred file size: 0 bytes
D | Literal data: 0 bytes
D | Matched data: 0 bytes
D | File list size: 0
D | File list generation time: 0.001 seconds
D | File list transfer time: 0.000 seconds
D | Total bytes sent: 429
D | Total bytes received: 147
D |
D | sent 429 bytes  received 147 bytes  384.00 bytes/sec
D | total size is 35,710  speedup is 62.00
E node servera2p2.lan.local synchronization failed (['/etc/opensvc/myapp.conf', u'/etc/opensvc/myapp.d'] => phoenixoboros@servera2p2.lan.local:/)
D refresh status: down => down
@ n:servera1p2.lan.local o:myapp rs:sync sc:n
D start sync post_action
D resources after tags[] filter: sync#i0
D resources after 'disable' filter: sync#i0
@ n:servera1p2.lan.local o:myapp r:fs#0 sc:n
D refresh status: up => up
@ n:servera1p2.lan.local o:myapp r:fs#1 sc:n
D refresh status: up => up
@ n:servera1p2.lan.local o:myapp r:fs#2 sc:n
D refresh status: up => up
@ n:servera1p2.lan.local o:myapp r:fs#3 sc:n
D refresh status: up => up
@ n:servera1p2.lan.local o:myapp r:ip#0 sc:n
D refresh status: up => up
@ n:servera1p2.lan.local o:myapp r:ip#1 sc:n
D refresh status: up => up
@ n:servera1p2.lan.local o:myapp sc:n
D get_cgroup_path : t=freezer, create=False
@ n:servera1p2.lan.local o:myapp rs:app sc:n
D get_cgroup_path : t=freezer, create=False
@ n:servera1p2.lan.local o:myapp r:app#5 sc:n
D get_cgroup_path : t=freezer, create=False
D acquire app lock (timeout 0, delay 1, action status, lockfile /var/lib/opensvc/svc/myapp/app#5/lock)
D release app lock
D /etc/opensvc/myapp.d/httpd status
D output:
D | httpd (pid  26710) is running...
D [u'/etc/opensvc/myapp.d/httpd', 'status'] returned out=[httpd (pid  26710) is running...], err=[], ret=[0]
D refresh status: undef => up
@ n:servera1p2.lan.local o:myapp sc:n
D get_cgroup_path : t=freezer, create=False
@ n:servera1p2.lan.local o:myapp rs:app sc:n
D get_cgroup_path : t=freezer, create=False
@ n:servera1p2.lan.local o:myapp r:app#4 sc:n
D get_cgroup_path : t=freezer, create=False
D acquire app lock (timeout 0, delay 1, action status, lockfile /var/lib/opensvc/svc/myapp/app#4/lock)
D release app lock
D /etc/opensvc/myapp.d/myapp status
D output:
D | Broker versement1; status: running
D | Consumer:
D |     - eventConsumer1: running
D |     - fullEventConsumer1: running
D |     - archiveConsumer1: running
D [u'/etc/opensvc/myapp.d/myapp', 'status'] returned out=[Broker versement1; status: running
Consumer:
    - eventConsumer1: running
    - fullEventConsumer1: running
    - archiveConsumer1: running], err=[], ret=[0]
D refresh status: undef => up
@ n:servera1p2.lan.local o:myapp sc:n
D get_cgroup_path : t=freezer, create=False
@ n:servera1p2.lan.local o:myapp rs:app sc:n
D get_cgroup_path : t=freezer, create=False
@ n:servera1p2.lan.local o:myapp r:app#1 sc:n
D get_cgroup_path : t=freezer, create=False
D acquire app lock (timeout 0, delay 1, action status, lockfile /var/lib/opensvc/svc/myapp/app#1/lock)
D release app lock
D /etc/opensvc/myapp.d/JournalServer status
D output:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/lib64/python2.7/logging/handlers.py", line 154, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/share/opensvc/opensvc/core/logger.py", line 97, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 467, in format
    s = self._fmt % record.__dict__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 24: ordinal not in range(128)
Logged from file __init__.py, line 638
D | journalserver-cons 1 démarré (PID : 69173)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/lib64/python2.7/logging/handlers.py", line 154, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/share/opensvc/opensvc/core/logger.py", line 97, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 467, in format
    s = self._fmt % record.__dict__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 20: ordinal not in range(128)
Logged from file __init__.py, line 638
D | logserver-vers 1 démarré (PID : 118477)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/lib64/python2.7/logging/handlers.py", line 154, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/share/opensvc/opensvc/core/logger.py", line 97, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 467, in format
    s = self._fmt % record.__dict__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 85: ordinal not in range(128)
Logged from file __init__.py, line 636
D [u'/etc/opensvc/myapp.d/JournalServer', 'status'] returned out=[journalserver-cons 1 démarré (PID : 69173)
logserver-vers 1 démarré (PID : 118477)], err=[], ret=[0]
D refresh status: undef => up
@ n:servera1p2.lan.local o:myapp sc:n
D get_cgroup_path : t=freezer, create=False
@ n:servera1p2.lan.local o:myapp rs:app sc:n
D get_cgroup_path : t=freezer, create=False
@ n:servera1p2.lan.local o:myapp r:app#0 sc:n
D get_cgroup_path : t=freezer, create=False
D acquire app lock (timeout 0, delay 1, action status, lockfile /var/lib/opensvc/svc/myapp/app#0/lock)
D release app lock
D /etc/opensvc/myapp.d/postgresql-11 status
D output:
D | postgresql-11 (pid  131779) is running...
D [u'/etc/opensvc/myapp.d/postgresql-11', 'status'] returned out=[postgresql-11 (pid  131779) is running...], err=[], ret=[0]
D refresh status: undef => up
@ n:servera1p2.lan.local o:myapp sc:n
D get_cgroup_path : t=freezer, create=False
@ n:servera1p2.lan.local o:myapp rs:app sc:n
D get_cgroup_path : t=freezer, create=False
@ n:servera1p2.lan.local o:myapp r:app#3 sc:n
D get_cgroup_path : t=freezer, create=False
D acquire app lock (timeout 0, delay 1, action status, lockfile /var/lib/opensvc/svc/myapp/app#3/lock)
D release app lock
D /etc/opensvc/myapp.d/myapp_brokers_webapps status
D output:
D | All versement brokers are up
D | Signer for /versement1 present
D [u'/etc/opensvc/myapp.d/myapp_brokers_webapps', 'status'] returned out=[All versement brokers are up
Signer for /versement1 present], err=[], ret=[0]
D refresh status: undef => up
@ n:servera1p2.lan.local o:myapp sc:n
D get_cgroup_path : t=freezer, create=False
@ n:servera1p2.lan.local o:myapp rs:app sc:n
D get_cgroup_path : t=freezer, create=False
@ n:servera1p2.lan.local o:myapp r:app#2 sc:n
D get_cgroup_path : t=freezer, create=False
D acquire app lock (timeout 0, delay 1, action status, lockfile /var/lib/opensvc/svc/myapp/app#2/lock)
D release app lock
D /etc/opensvc/myapp.d/tomcat9 status
D output:
D | tomcat9 (pid 24030) is running...
D [u'/etc/opensvc/myapp.d/tomcat9', 'status'] returned out=[tomcat9 (pid 24030) is running...], err=[], ret=[0]
D refresh status: undef => up
@ n:servera1p2.lan.local o:myapp r:sync#i0 sc:n
D refresh status: down => down
@ n:servera1p2.lan.local o:myapp r:disk#0 sc:n
D drbdadm dstate add-myapp
D output:
D | UpToDate/UpToDate
D refresh status: stdby up => stdby up
@ n:servera1p2.lan.local o:myapp r:disk#1 sc:n
D drbdadm dstate pgsql-myapp
D output:
D | UpToDate/UpToDate
D refresh status: stdby up => stdby up
@ n:servera1p2.lan.local o:myapp r:disk#2 sc:n
D drbdadm dstate amq-myapp
D output:
D | UpToDate/UpToDate
D refresh status: stdby up => stdby up
@ n:servera1p2.lan.local o:myapp r:disk#3 sc:n
D drbdadm dstate journal-myapp
D output:
D | UpToDate/UpToDate
D refresh status: stdby up => stdby up
```


```
[phoenixoboros@servera2p2 ~]# sudo sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   permissive
Mode from config file:          disabled
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      31
[phoenixoboros@servera2p2 ~]#
```

It is icompatible with selinux in permissive mode?

Regards,

**Comment by cvaroqui** [comment]
By default opensvc configures the sync#i0 resource to preserve xattrs, using the -X rsync option.
So you have to options:
1/ setup selinux so the rsync -X works
2/ disable xattrs replication

Though we cannot guide through solution 1/, the configuration to implement solution 2/ is:

```
[sync#i0]
reset_options = true
options = -HApogDtrlvx --stats --delete --force
```

**Comment by cvaroqui** [comment]
Side note,

As you seem to have utf-8 outputs from your start-up scripts, I think it would be better to switch the opensvc interpreter to python3, where utf-8 handling is better.

This can be achieved either by
1/ installing opensvc after python3 is installed (the opensvc postinstall will then prefer py3 over py2)
2/ forcing python3 in /etc/sysconfig/opensvc (redhat like) or /etc/default/opensvc (debian like). in this case a daemon restart is necessary after the change
